apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-k8s-demo-api
  labels:
    app: {{ .Release.Name }}-k8s-demo-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-k8s-demo-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-k8s-demo-api
    spec:
      containers:
        - name: k8s-demo-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
