name: Build and Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t k8s-demo-api:ci ./app

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint ./helm/k8s-demo-api

      - name: Render Helm templates (dry run)
        run: helm template test-release ./helm/k8s-demo-api
